name: Test and deploy

on:
  push:
    branches:
      - master
    paths: # 指定哪些文件改变时触发
      - packages/**
      - package.json

jobs:
 setup:
    name: Setup environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: npm install -g pnpm@^6.14.7

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
    test:
    name: Run Lint and Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build hooks
        run: npm run build-hooks
      - name: Run tests
        run: pnpm run test

    build:
    name: Build docs
    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Build docs
        run: pnpm run docs:build
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./packages/docs/.vitepress/dist

    deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download docs
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .
